# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.61.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    ensure_git_status_clean

    increment_build_number
    increment_version_number version_number: "1.0.1"
  end

  lane :appstore do
    gym(
      scheme: "NumPadApp",
      clean: true
    )
    deliver(
      app_identifier: "com.morevoltage.NumPad",
      username: "efremidzel@hotmail.com",
      skip_screenshots: true,
      skip_metadata: true,
      force: true
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )

    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts

    # Tag release and push to GitHub
    build = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    version = Actions.lane_context[Actions::SharedValues::VERSION_NUMBER]
    commit_version_bump message: "Build #{build}"
    add_git_tag tag: "#{version}-#{build}"
    push_to_git_remote
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
